<?php
/*//Uncomment this line (and the end curly bracket) to loop through more songs
//for ($x = 0 ; $x < 50; $x = $X+=50){
	//echo $x.'<br><br>';
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$x=0;
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.spotify.com/v1/me/tracks?limit=50&offset=".$x."");

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Authorization: Bearer BQANsZBH5B8eiLYTqAyHPFtH7L71EV0CxZsRLydpU4JwDJcFmcB_ovLvZbCnSDa1yp0FjqEToWgsyO8GQxAPetg-3l_djDMUviIED1oVTNd9Y1H0-wRs4ZiLhs9zcrkmd1lqPpQOA8nvpFo9pXArK4I";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$result = json_decode($result, true);
for ($i = 0 ; $i < count($result['items']); $i++){
print_r($result['items'][$i]['track']['album']['artists'][0]['name']);
echo '- ';
print_r($result['items'][$i]['track']['name']);
echo ' lyrics video<br>';
}
//echo '<pre>'; print_r($result); echo '</pre>';
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

//}
//^^^This is the curly that needs to be un-commented to loop the query*/
?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>title</title>
  </head>
  <body>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>

  <div id="responseText"></div>

  <div class="single"></div>

  <a href="#" onclick="startSearch();">Click Me!</a>

    <script src="js/ajax-request.js" type="text/javascript"></script>

    <?php
/**
 * FFMPEG-PHP Test Script
 *
 * Special thanks to http://www.sajithmr.me/ffmpeg-sample-code for this code example!
 * See the tutorial at http://myownhomeserver.com on how to install ffmpeg-php.
 */
// Check if the ffmpeg-php extension is loaded first
extension_loaded('ffmpeg') or die('Error in loading ffmpeg');
 
// Determine the full path for our video
$vid = realpath('./vid2.avi');
 
// Create the ffmpeg instance and then display the information about the video clip.
$ffmpegInstance = new ffmpeg_movie($vid);
echo "getDuration: " . $ffmpegInstance->getDuration() . "<br />".
"getFrameCount: " . $ffmpegInstance->getFrameCount() . "<br />".
"getFrameRate: " . $ffmpegInstance->getFrameRate() . "<br />".
"getFilename: " . $ffmpegInstance->getFilename() . "<br />".
"getComment: " . $ffmpegInstance->getComment() . "<br />".
"getTitle: " . $ffmpegInstance->getTitle() . "<br />".
"getAuthor: " . $ffmpegInstance->getAuthor() . "<br />".
"getCopyright: " . $ffmpegInstance->getCopyright() . "<br />".
"getArtist: " . $ffmpegInstance->getArtist() . "<br />".
"getGenre: " . $ffmpegInstance->getGenre() . "<br />".
"getTrackNumber: " . $ffmpegInstance->getTrackNumber() . "<br />".
"getYear: " . $ffmpegInstance->getYear() . "<br />".
"getFrameHeight: " . $ffmpegInstance->getFrameHeight() . "<br />".
"getFrameWidth: " . $ffmpegInstance->getFrameWidth() . "<br />".
"getPixelFormat: " . $ffmpegInstance->getPixelFormat() . "<br />".
"getBitRate: " . $ffmpegInstance->getBitRate() . "<br />".
"getVideoBitRate: " . $ffmpegInstance->getVideoBitRate() . "<br />".
"getAudioBitRate: " . $ffmpegInstance->getAudioBitRate() . "<br />".
"getAudioSampleRate: " . $ffmpegInstance->getAudioSampleRate() . "<br />".
"getVideoCodec: " . $ffmpegInstance->getVideoCodec() . "<br />".
"getAudioCodec: " . $ffmpegInstance->getAudioCodec() . "<br />".
"getAudioChannels: " . $ffmpegInstance->getAudioChannels() . "<br />".
"hasAudio: " . $ffmpegInstance->hasAudio();
?>

 <script>
 function startSearch() {
 $.get("search.php");
 return false;
 }
 </script>

  </body>
</html>